### ISSUE TITLE
touch issue

### ISSUE THREAD

**Issue by leoirti** [muchenspace/jniRootImgui#2]
touch breaks (android 14)
cant touch any other app or menu except the imgui menu.

**Comment by muchenspace** [comment]
这是因为android14新加入的特性，目前我也不知道如何解决，sorry

**Comment by muchenspace** [comment]
Run the following command to resolve the problem

adb shell settings put global block_untrusted_touches 0

**Comment by muchenspace** [comment]
已经解决，请你重新下载源码并编译

**Comment by leoirti** [comment]
giving black screen now. menu doesnt show up

**Comment by muchenspace** [comment]
Yeah, but there's nothing I can do，sorry

**Comment by muchenspace** [comment]
解决了
https://github.com/muchenspace/closeUntrustedTouchEventsAreBlocked

**Comment by muchenspace** [comment]
hi?
